// TypeScript declarations for the OnionPIR WASM client module.
// Generated by hand — matches the embind registrations in bindings.cpp.

export interface OnionPirModule {
    /**
     * Create a new PIR client for a database with the given number of entries.
     * Pass numEntries=0 for key generation only (keys are independent of DB size).
     * Call .delete() when done to free WASM heap memory.
     */
    OnionPirClient: {
        new(numEntries: number): OnionPirClient;
    };

    /**
     * Create a PIR client from an existing secret key.
     * Use this to create per-database clients that share the same encryption keys
     * but use the correct numEntries for query generation and response decryption.
     * Call .delete() when done to free WASM heap memory.
     *
     * @param numEntries - Database entry count (must match the server)
     * @param clientId - Client ID from the original key-generation client
     * @param secretKey - Secret key bytes from exportSecretKey()
     */
    createClientFromSecretKey(numEntries: number, clientId: number, secretKey: Uint8Array): OnionPirClient;

    /**
     * Get PIR database parameters for a given number of entries.
     * The returned numEntries may be larger than requested due to padding.
     */
    paramsInfo(numEntries: number): ParamsInfo;

    /**
     * splitmix64 hash function.
     * Note: uses JS number (double), so precision is limited to 2^53.
     * For full 64-bit precision, use BigInt-based wrappers on the JS side.
     */
    splitmix64(x: number): number;

    /**
     * Compute a single cuckoo bucket index for an entry.
     * @param entryId - The entry identifier
     * @param key - Hash function key (as number, limited to 2^53 precision)
     * @param numBins - Number of bins in the hash table
     * @returns Bucket index in [0, numBins)
     */
    cuckooHashInt(entryId: number, key: number, numBins: number): number;

    /**
     * Build a complete cuckoo hash table for a group.
     * Uses deterministic eviction matching the Rust server exactly.
     * @param entries - Uint32Array of entry IDs assigned to this group
     * @param keys - Uint32Array of length num_keys*2, encoding each uint64 key
     *               as [lo32, hi32] pairs to avoid double precision loss.
     *               Example for 6 keys: Uint32Array of length 12.
     * @param numBins - Table size
     * @returns Uint32Array where table[bin] = entry_id (0xFFFFFFFF for empty)
     */
    buildCuckooBs1(entries: Uint32Array, keys: Uint32Array, numBins: number): Uint32Array;
}

export interface OnionPirClient {
    /** Get this client's unique ID (for server key registration). */
    id(): number;

    /**
     * Export the client's secret key for creating per-database clients.
     * Use with createClientFromSecretKey() to create clients with correct
     * numEntries while sharing the same encryption keys.
     */
    exportSecretKey(): Uint8Array;

    /** Generate Galois keys to send to the server. ~379 KB. */
    generateGaloisKeys(): Uint8Array;

    /** Generate GSW keys to send to the server. ~324 KB. */
    generateGswKeys(): Uint8Array;

    /**
     * Generate a PIR query for the entry at the given index.
     * @param entryIndex - Index of the desired entry (0-based)
     * @returns Serialized query bytes (~16 KB)
     */
    generateQuery(entryIndex: number): Uint8Array;

    /**
     * Decrypt the server's response and extract the plaintext entry bytes.
     * @param entryIndex - Same index used in generateQuery
     * @param response - Server response bytes
     * @returns Plaintext entry (3840 bytes)
     */
    decryptResponse(entryIndex: number, response: Uint8Array): Uint8Array;

    /** Free WASM heap memory. Must call when done with the client. */
    delete(): void;
}

export interface ParamsInfo {
    /** Total entries in the DB (after padding — may be larger than requested). */
    numEntries: number;
    /** Bytes per entry. */
    entrySize: number;
    /** Total plaintext count (fstDimSz × otherDimSz). */
    numPlaintexts: number;
    /** First dimension size. */
    fstDimSz: number;
    /** Number of chunks / other dimension size. */
    otherDimSz: number;
    /** Number of uint64 values per NTT-expanded plaintext. */
    coeffValCnt: number;
}

/**
 * Initialize the OnionPIR WASM module.
 * Returns a promise that resolves when the WASM binary is loaded and compiled.
 *
 * Usage:
 * ```typescript
 * import createOnionPirModule from './onionpir_client.js';
 * const Module = await createOnionPirModule();
 * const client = new Module.OnionPirClient(65536);
 * ```
 */
declare function createOnionPirModule(): Promise<OnionPirModule>;
export default createOnionPirModule;
